### ISSUE TITLE
Issue with Displaying Search

### ISSUE THREAD

**Issue by davidshq** [bigboomdesign/big-boom-directory#2]
Hi All,

I'm running a vanilla WP instance using the Twenty-Sixteen theme. I've created a page and added the following:

[bbd-search]

Which shows only the search button but no search input.

(Pressing the search button returns all results)

I read the documentation (yes, in that order) and saw that I needed to setup a widget to make this work - so I did (the Big Boom Directory Search widget) and then I added the following to the above page:

[bbd-search widget_id="2"]

Unfortunately I'm still experiencing the same issue.

Here is the actual code that is being created by the shortcode and output onto the test page:

```
	<div class="entry-content">
		<div class="widget bbd-search-widget">
                      <h2 class="widgettitle">Search!</h2>		
                       <div class='bbd-search-widget-container'>
		                   <form method="post" 
                                           id="bbd-search-form" 
			                    action="http://localhost/wordpress/sample-page/"
		                     >
			                    <input type="hidden" 
				                    name="bbd_search[widget_id]" 
				                    value="bbd_search_widget-2" 
			                      />
			                     <input type="hidden" 
				                    name="bbd_search[widget_number]" 
				                    value="2" 
			                      />
			                     <input class="bbd-search-submit" type="submit" value="Search" />
		                     </form>
		           </div>
                           <!-- .bbd-search-widget-container -->
		</div>
	</div><!-- .entry-content -->
```
After some further experiments I see that I need to go to the widget and under custom field filters select a specific field I want it to search. Is this correct?

**Comment by mhull** [comment]
Hello Dave,

That is correct.  You will want to select at least one Taxonomy Filter or Custom Field Filter for the widget.  This is what provides the mechanism to narrow down the posts on the results page.
